# Generated by Django 5.0.6 on 2024-06-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_role_note_user_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="api.role"
            ),
            preserve_default=False,
        ),
    ]
