# Generated by Django 5.0.6 on 2024-06-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_refreshtoken_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="user",),
        migrations.AddField(
            model_name="note",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_doctor",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_patient",
                to="api.user",
            ),
        ),
    ]
