# Generated by Django 5.0.6 on 2024-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_note_user_note_doctor_note_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="creation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
